import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import SearchAppBar from "@/components/navBar";
import MultiActionAreaCard from "@/components/pokeCard";
import { Container } from "@mui/material";
import axios from "axios";
import { useEffect, useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemons, setPokemons] = useState<any[]>([]);

  useEffect(() => {
    getPokemons();
  }, []);

  const getPokemons = () => {
    let endpoints = [];

    for (let i = 1; i < 352; i++) {
      endpoints.push(`https://pokeapi.co/api/v2/pokemon/${i}/`);
    }

    console.log(endpoints);

    let response = axios
      .all(endpoints.map((endpoint) => axios.get(endpoint)))
      .then((res) => setPokemons(res))
      .catch((err) => console.log(err));
    return response;
  };

  const searchPokemon = (searchedPokemon: any) => {
    let searchMatch = [];

    if (searchedPokemon === "") {
      getPokemons();
    }

    for (let i in pokemons) {
      if (pokemons[i].data.name.startsWith(searchedPokemon)) {
        searchMatch.push(pokemons[i]);
      }
    }

    setPokemons(searchMatch);
  };

  return (
    <>
      <Head>
        <title>Lucy&apos;s Great Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchAppBar searchPokemon={searchPokemon} />
        <section>
          <Container maxWidth="xl">
            <div className={styles.divLine}>
              {pokemons.map((pokemon: any) => (
                <Link
                  href={`/pokemon/${pokemon.data.name}`}
                  target="_blank"
                  key={`/pokemon/${pokemon.data.id}`}
                >
                  <MultiActionAreaCard
                    name={pokemon.data.name}
                    image={pokemon.data.sprites.front_default}
                    types={pokemon.data.types}
                  />
                </Link>
              ))}
            </div>
          </Container>
        </section>
      </main>
    </>
  );
}
