import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import SearchAppBar from "@/components/navBar";
import MultiActionAreaCard from "@/components/pokeCard";
import { Container } from "@mui/material";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [pokemons, setPokemons] = useState<any[]>([]);

  useEffect(() => {
    getPokemons();
  }, []);

  const getPokemons = () => {
    axios
      .get("https://pokeapi.co/api/v2/pokemon?limit=151&offset=0")
      .then((res) => setPokemons(res.data.results))
      .catch((err) => console.log(err));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchAppBar />
        <section>
          <Container>
            <div className={styles.divLine}>
              {pokemons.map((pokemon) => (
                <MultiActionAreaCard name={pokemon.name} />
              ))}
            </div>
          </Container>
        </section>
      </main>
    </>
  );
}
